org.gradle.jvmargs = -Xmx3G

modGroup = gregtechlite.gtlitecore
modId = gtlitecore
modName = GregTech Lite Core
modVersion = 1.0.0

minecraftVersion = 1.12.2
userName = Magic_Sweepy

usesMixins = true
usesAccessTransformer = true

usesCoreMod = true
includeMod = true
coreModPluginPath = gregtechlite.gtlitecore.mixins.EarlyMixinLoader

generateTokenPath = gregtechlite.gtlitecore.api.GTLiteTags