package magicbook.gtlitecore.api.unification

import gregtech.api.unification.material.Material
import magicbook.gtlitecore.api.unification.material.GTLiteElementMaterials
import magicbook.gtlitecore.api.unification.material.GTLiteFirstDegreeMaterials
import magicbook.gtlitecore.api.unification.material.GTLiteOrganicChemistryMaterials
import magicbook.gtlitecore.api.unification.material.GTLiteSecondDegreeMaterials
import magicbook.gtlitecore.api.unification.material.GTLiteThirdDegreeMaterials
import magicbook.gtlitecore.api.unification.material.GTLiteUnknownCompositionMaterials

@Suppress("MISSING_DEPENDENCY_CLASS")
class GTLiteMaterials
{

    companion object
    {
        // 1-2000: Element Materials
        lateinit var Adamantium: Material
        lateinit var Vibranium: Material
        lateinit var Taranium: Material
        lateinit var MetastableFlerovium: Material
        lateinit var MetastableOganesson: Material
        lateinit var MetastableHassium: Material
        lateinit var CosmicNeutronium: Material
        lateinit var Infinity: Material
        lateinit var Plutonium244: Material
        lateinit var DegenerateRhenium: Material
        lateinit var Magnetium: Material
        lateinit var Rhugnor: Material
        lateinit var Hypogen: Material
        lateinit var Shirabon: Material

        // 2001-4000: First Degree Materials
        lateinit var Dolomite: Material
        lateinit var Tanzanite: Material
        lateinit var Azurite: Material
        lateinit var Forsterite: Material
        lateinit var Augite: Material
        lateinit var Lizardite: Material
        lateinit var Muscovite: Material
        lateinit var Clinochlore: Material
        lateinit var Albite: Material
        lateinit var Fluorite: Material
        lateinit var Anorthite: Material
        lateinit var Oligoclase: Material
        lateinit var Labradorite: Material
        lateinit var Bytownite: Material
        lateinit var Tenorite: Material
        lateinit var Cuprite: Material
        lateinit var Wollastonite: Material
        lateinit var Fluorapatite: Material
        lateinit var Kaolinite: Material
        lateinit var Lignite: Material
        lateinit var Firestone: Material
        lateinit var Iron3Sulfate: Material
        lateinit var Celestine: Material
        lateinit var Strontianite: Material
        lateinit var StrontiumOxide: Material
        lateinit var StrontiumSulfide: Material
        lateinit var Alumina: Material
        lateinit var Phlogopite: Material
        lateinit var Baddeleyite: Material
        lateinit var Nephelite: Material
        lateinit var Aegirine: Material
        lateinit var NiobiumPentoxide: Material
        lateinit var TantalumPentoxide: Material
        lateinit var CalciumDifluoride: Material
        lateinit var ManganeseDifluoride: Material
        lateinit var HeavyAlkaliChloridesSolution: Material
        lateinit var TinDichloride: Material
        lateinit var TinTetrachloride: Material
        lateinit var CaesiumHexachlorotinate: Material
        lateinit var RubidiumHexachlorotinate: Material
        lateinit var Cryolite: Material
        lateinit var AluminiumHydroxide: Material
        lateinit var SodiumAluminate: Material
        lateinit var SodiumCarbonate: Material
        lateinit var AluminiumSulfate: Material
        lateinit var ZSM5: Material
        lateinit var MolybdenumTrioxide: Material
        lateinit var MolybdenumFlue: Material
        lateinit var LeadDichloride: Material
        lateinit var TraceRheniumFlue: Material
        lateinit var PerrhenicAcid: Material
        lateinit var AmmoniumPerrhenate: Material
        lateinit var Jade: Material
        lateinit var Jasper: Material
        lateinit var Picotite: Material
        lateinit var ManganeseMonoxide: Material
        lateinit var LeadChromate: Material
        lateinit var LeadNitrate: Material
        lateinit var CobaltAluminate: Material
        lateinit var Orpiment: Material
        lateinit var SodiumChlorate: Material
        lateinit var SodiumPerchlorate: Material
        lateinit var SodiumHypochlorite: Material
        lateinit var TungstenTrioxide: Material
        lateinit var StrontiumFerrite: Material
        lateinit var TitaniumNitrate: Material
        lateinit var LithiumTitanate: Material
        lateinit var PalladiumNitrate: Material
        lateinit var PalladiumAcetate: Material
        lateinit var PalladiumLoadedRutileNanoparticles: Material
        lateinit var LithiumOxide: Material
        lateinit var LithiumCarbonate: Material
        lateinit var BlueVitriol: Material
        lateinit var SodiumTellurite: Material
        lateinit var SeleniumDioxide: Material
        lateinit var TelluriumDioxide: Material
        lateinit var SelenousAcid: Material
        lateinit var AluminiumSelenide: Material
        lateinit var HydrogenSelenide: Material
        lateinit var CadmiumBromide: Material
        lateinit var MagnesiumBromide: Material
        lateinit var HRAMagnesium: Material
        lateinit var HydrobromicAcid: Material
        lateinit var Dimethylcadmium: Material
        lateinit var CadmiumSelenide: Material
        lateinit var Prasiolite: Material
        lateinit var ZBLANGlass: Material
        lateinit var ErbiumDopedZBLANGlass: Material
        lateinit var PraseodymiumDopedZBLANGlass: Material
        lateinit var Ozone: Material
        lateinit var CubicZirconia: Material
        lateinit var BismuthTelluride: Material
        lateinit var MagnetoResonatic: Material
        lateinit var LanthanumOxide: Material
        lateinit var CeriumOxide: Material
        lateinit var PraseodymiumOxide: Material
        lateinit var NeodymiumOxide: Material
        lateinit var SamariumOxide: Material
        lateinit var EuropiumOxide: Material
        lateinit var GadoliniumOxide: Material
        lateinit var TerbiumOxide: Material
        lateinit var DysprosiumOxide: Material
        lateinit var HolmiumOxide: Material
        lateinit var ErbiumOxide: Material
        lateinit var ThuliumOxide: Material
        lateinit var YtterbiumOxide: Material
        lateinit var LutetiumOxide: Material
        lateinit var ScandiumOxide: Material
        lateinit var YttriumOxide: Material
        lateinit var PromethiumOxide: Material
        lateinit var LaPrNdCeOxidesSolution: Material
        lateinit var ScEuGdSmOxidesSolution: Material
        lateinit var YTbDyHoOxidesSolution: Material
        lateinit var ErTmYbLuOxidesSolution: Material
        lateinit var PlatinumGroupResidue: Material
        lateinit var PlatinumGroupConcentrate: Material
        lateinit var PurifiedPlatinumGroupConcentrate: Material
        lateinit var AmmoniumHexachloroplatinate: Material
        lateinit var AmmoniumHexachloropalladate: Material
        lateinit var SodiumNitrate: Material
        lateinit var HexachloroplatinicAcid: Material
        lateinit var CarbonTetrachloride: Material
        lateinit var SodiumPeroxide: Material
        lateinit var RutheniumTrichloride: Material
        lateinit var RhodiumTrioxide: Material
        lateinit var SulfurDichloride: Material
        lateinit var OsmiumTetrachloride: Material
        lateinit var BerylliumOxide: Material
        lateinit var HydrogenPeroxide: Material
        lateinit var GrapheneOxide: Material
        lateinit var YttriumNitrate: Material
        lateinit var BariumNitrate: Material
        lateinit var CopperNitrate: Material
        lateinit var YttriumBariumCopperOxidesMixture: Material
        lateinit var GSTGlass: Material
        lateinit var GermaniumDioxide: Material
        lateinit var RoastedSphalerite: Material
        lateinit var ZincRichSphalerite: Material
        lateinit var WaelzOxide: Material
        lateinit var WaelzSlag: Material
        lateinit var PiranhaSolution: Material
        lateinit var HydroxyquinolineAluminium: Material
        lateinit var HydroselenicAcid: Material
        lateinit var CopperGalliumIndiumSelenide: Material
        lateinit var BariumHydroxide: Material
        lateinit var BariumTitanate: Material
        lateinit var SamariumCobalt: Material
        lateinit var PotassiumHydroxide: Material
        lateinit var CopperDichloride: Material
        lateinit var SodiumCyanide: Material
        lateinit var PotassiumBromate: Material
        lateinit var WhitePhosphorus: Material
        lateinit var RedPhosphorus: Material
        lateinit var VioletPhosphorus: Material
        lateinit var BlackPhosphorus: Material
        lateinit var BluePhosphorus: Material
        lateinit var PhosphorusTrichloride: Material
        lateinit var SodiumFluoride: Material
        lateinit var SodiumTrifluoroethanolate: Material
        lateinit var TechnetiumHeptaoxide: Material
        lateinit var TriniumTrioxide: Material
        lateinit var Pertechnetate: Material
        lateinit var AmmoniumNitrate: Material
        lateinit var AmmoniumPertechnetate: Material
        lateinit var TechnetiumDioxide: Material
        lateinit var IndiumPhosphate: Material
        lateinit var GalliumDioxide: Material
        lateinit var CalciumSulfide: Material
        lateinit var RP1RocketFuel: Material
        lateinit var BismuthTrioxide: Material
        lateinit var BismuthStrontiumCalciumCuprate: Material
        lateinit var Bedrockium: Material
        lateinit var Adamantite: Material
        lateinit var AdamantiumUnstable: Material
        lateinit var AdamantiumEnriched: Material
        lateinit var VibraniumUnstable: Material
        lateinit var DeepIron: Material
        lateinit var SodiumPotassiumEutatic: Material
        lateinit var LeadBismuthEutatic: Material
        lateinit var LithiumFluoride: Material
        lateinit var PotassiumFluoride: Material
        lateinit var LithiumSodiumPotassiumFluorides: Material
        lateinit var BerylliumDifluoride: Material
        lateinit var LithiumBerylliumFluorides: Material
        lateinit var FleroviumYtterbiumPlasma: Material
        lateinit var RubidiumTitanate: Material
        lateinit var SodiumTitanate: Material
        lateinit var RubidiumChloride: Material
        lateinit var SodiumOxide: Material
        lateinit var SodiumAcetate: Material
        lateinit var CaesiumBromide: Material
        lateinit var FranciumBromide: Material
        lateinit var FranciumCaesiumCadmiumBromide: Material
        lateinit var SodiumSeaborgate: Material
        lateinit var LeadScandiumTantalate: Material
        lateinit var ThalliumSulfate: Material
        lateinit var ThalliumBariumCalciumCuprate: Material
        lateinit var PotassiumManganate: Material
        lateinit var PotassiumPermanganate: Material
        lateinit var LanthanumGalliumManganate: Material
        lateinit var BariumStrontiumTitanate: Material
        lateinit var LutetiumManganeseGermanium: Material
        lateinit var BoricAcid: Material
        lateinit var BoronTrioxide: Material
        lateinit var BoronTrifluoride: Material
        lateinit var LithiumHydride: Material
        lateinit var LithiumTetrafluoroborate: Material
        lateinit var BoronTrichloride: Material
        lateinit var HexagonalBoronNitride: Material
        lateinit var CubicBoronNitride: Material
        lateinit var AmorphousBoronNitride: Material
        lateinit var Heterodiamond: Material
        lateinit var CubicHeterodiamond: Material
        lateinit var CalciumCarbide: Material
        lateinit var CalciumHydroxide: Material
        lateinit var ChromiumGermaniumTelluride: Material
        lateinit var ChromiumGermaniumTellurideMagnetic: Material
        lateinit var GalliumTrichloride: Material
        lateinit var GalliumTrioxide: Material
        lateinit var GalliumNitride: Material
        lateinit var AluminiumTrichloride: Material
        lateinit var NiobiumPentachloride: Material
        lateinit var LithiumNiobate: Material
        lateinit var ManganeseSulfate: Material
        lateinit var PotassiumSulfate: Material
        lateinit var NeodymiumDopedYttriumOxide: Material
        lateinit var AluminiumNitrate: Material
        lateinit var ChlorinatedSolvents: Material
        lateinit var AluminaSolution: Material
        lateinit var NdYAG: Material
        lateinit var ScandiumTitaniumMixture: Material
        lateinit var RadiumRadonMixture: Material
        lateinit var PoloniumNitrate: Material
        lateinit var SodiumPolonate: Material
        lateinit var PoloniumDioxide: Material
        lateinit var UranylChlorideSolution: Material
        lateinit var UranylNitrateSolution: Material
        lateinit var RadiumSulfate: Material
        lateinit var LeadSulfate: Material
        lateinit var ThoriumNitrate: Material
        lateinit var RadiumDichloride: Material
        lateinit var ThoriumDioxide: Material
        lateinit var UranylNitrate: Material
        lateinit var BariumOxide: Material
        lateinit var WoodsGlass: Material
        lateinit var PotassiumTertbutoxide: Material
        lateinit var CaesiumHydroxide: Material
        lateinit var CaesiumCarbonate: Material
        lateinit var SodiumHydride: Material
        lateinit var VanadiumPentoxide: Material
        lateinit var ActiniumOxalate: Material
        lateinit var ActiniumTrihydride: Material
        lateinit var ActiniumSuperhydride: Material
        lateinit var SodiumFormate: Material
        lateinit var SodiumThiosulfate: Material
        lateinit var LithiumThiinediselenide: Material
        lateinit var BETSPerrhenate: Material
        lateinit var HeliumNeon: Material
        lateinit var GermaniumTetrachloride: Material
        lateinit var SiliconTetrachloride: Material
        lateinit var CaesiumCeriumCobaltIndium: Material
        lateinit var MercuryCadmiumTelluride: Material
        lateinit var ThalliumRoentgeniumChloride: Material
        lateinit var SilicaGelBase: Material
        lateinit var SilicaGel: Material
        lateinit var NitroniumTetrafluoroborate: Material
        lateinit var NitrosoniumTetrafluoroborate: Material
        lateinit var TetrafluoroboricAcid: Material
        lateinit var PotassiumFormate: Material
        lateinit var AmmoniumSulfate: Material
        lateinit var AmmoniumCarbonate: Material
        lateinit var AmmoniumAcetate: Material
        lateinit var SodiumAzanide: Material
        lateinit var SodiumAzide: Material
        lateinit var PalladiumBisdibenzylidieneacetone: Material
        lateinit var PotassiumTetrachloroplatinate: Material
        lateinit var AmmoniumPersulfate: Material
        lateinit var SilverTetrafluoroborate: Material
        lateinit var SilverChloride: Material
        lateinit var SilverOxide: Material
        lateinit var HeavyQuarkEnrichedMixture: Material
        lateinit var DeuteriumSuperheavyMixture: Material
        lateinit var HeavyQuarkDegenerateMatter: Material
        lateinit var QuantumchromodynamicallyConfinedMatter: Material
        lateinit var SodiumEthoxide: Material
        lateinit var Iron2Chloride: Material
        lateinit var PalladiumFullereneMatrix: Material
        lateinit var LuTmYChloridesSolution: Material
        lateinit var SodiumVanadate: Material
        lateinit var LuTmDopedYttriumVanadateDeposition: Material
        lateinit var LuTmYVO: Material
        lateinit var HexagonalSiliconNitride: Material
        lateinit var CubicSiliconNitride: Material
        lateinit var CeriumCarbonate: Material
        lateinit var DielectricFormationMixture: Material
        lateinit var ChloroauricAcid: Material
        lateinit var CadmiumSulfide: Material
        lateinit var BismuthChalcogenide: Material
        lateinit var PlutoniumTrihydride: Material
        lateinit var PlutoniumPhosphide: Material
        lateinit var Phosphine: Material

        // 4001-6000: Second Degree Materials
        lateinit var Kovar: Material
        lateinit var MaragingSteel250: Material
        lateinit var Inconel625: Material
        lateinit var Staballoy: Material
        lateinit var Talonite: Material
        lateinit var Zeron100: Material
        lateinit var WatertightSteel: Material
        lateinit var Stellite: Material
        lateinit var Tumbaga: Material
        lateinit var EglinSteelBase: Material
        lateinit var EglinSteel: Material
        lateinit var Grisium: Material
        lateinit var BabbitAlloy: Material
        lateinit var SiliconCarbide: Material
        lateinit var HSLASteel: Material
        lateinit var IncoloyMA813: Material
        lateinit var Monel500: Material
        lateinit var IncoloyMA956: Material
        lateinit var ZirconiumCarbide: Material
        lateinit var TantalumCarbide: Material
        lateinit var MolybdenumDisilicide: Material
        lateinit var HastelloyC276: Material
        lateinit var HastelloyX: Material
        lateinit var HastelloyN: Material
        lateinit var AluminiumBronze: Material
        lateinit var ReneN5: Material
        lateinit var TitaniumCarbide: Material
        lateinit var TitaniumTungstenCarbide: Material
        lateinit var Trinaquadalloy: Material
        lateinit var EnrichedNaquadahAlloy: Material
        lateinit var QuantumAlloy: Material
        lateinit var HDCS: Material
        lateinit var TitanSteel: Material
        lateinit var Tairitsium: Material
        lateinit var HalkoniteSteel: Material
        lateinit var HastelloyX78: Material
        lateinit var HastelloyK243: Material
        lateinit var Pikyonium64B: Material
        lateinit var ArceusAlloy2B: Material
        lateinit var VibraniumTritaniumActiniumIronSuperhydride: Material
        lateinit var HafniumCarbide: Material
        lateinit var SeaborgiumCarbide: Material
        lateinit var TantalumHafniumSeaborgiumCarbide: Material
        lateinit var SuperheavyAlloyA: Material
        lateinit var SuperheavyAlloyB: Material
        lateinit var PreciousMetalAlloy: Material
        lateinit var Nitinol60: Material

        // 6001-8000: Third Degree Materials
        lateinit var Limestone: Material
        lateinit var Komatiite: Material
        lateinit var GreenSchist: Material
        lateinit var BlueSchist: Material
        lateinit var Kimberlite: Material
        lateinit var Slate: Material
        lateinit var Shale: Material

        lateinit var BlazingPyrotheum: Material
        lateinit var GelidCryotheum: Material
        lateinit var TectonicPetrotheum: Material
        lateinit var ZephyreanAerotheum: Material
        lateinit var Sienna: Material
        lateinit var BurntSienna: Material

        lateinit var SuperheatedSteam: Material
        lateinit var SuperheatedSodiumPotassiumEutatic: Material
        lateinit var SuperheatedLeadBismuthEutatic: Material
        lateinit var SuperheatedLithiumSodiumPotassiumFluorides: Material
        lateinit var SuperheatedLithiumBerylliumFluorides: Material
        lateinit var SupercriticalSteam: Material
        lateinit var SupercriticalSodiumPotassiumEutatic: Material
        lateinit var SupercriticalLeadBismuthEutatic: Material
        lateinit var SupercriticalLithiumSodiumPotassiumFluorides: Material
        lateinit var SupercriticalLithiumBerylliumFluorides: Material

        // 8001-12000: Organic Chemistry Materials
        lateinit var Dicyclopentadiene: Material
        lateinit var Pentane: Material
        lateinit var Polyisoprene: Material
        lateinit var ParaXylene: Material
        lateinit var Nitrotoluene: Material
        lateinit var DiaminostilbenedisulfonicAcid: Material
        lateinit var SuccinicAcid: Material
        lateinit var Butanediol: Material
        lateinit var Tetrahydrofuran: Material
        lateinit var EthyleneDibromide: Material
        lateinit var GrignardReagent: Material
        lateinit var Ethylhexanol: Material
        lateinit var DiethylhexylPhosphoricAcid: Material
        lateinit var FormicAcid: Material
        lateinit var MethylFormate: Material
        lateinit var ThionylChloride: Material
        lateinit var PhthalicAnhydride: Material
        lateinit var Ethylanthraquinone: Material
        lateinit var Ethylanthrahydroquinone: Material
        lateinit var Hydrazine: Material
        lateinit var CitricAcid: Material
        lateinit var Glutamine: Material
        lateinit var LinoleicAcid: Material
        lateinit var Biotin: Material
        lateinit var Durene: Material
        lateinit var PyromelliticDianhydride: Material
        lateinit var Aminophenol: Material
        lateinit var Aniline: Material
        lateinit var Oxydianiline: Material
        lateinit var KaptonK: Material
        lateinit var BiphenylTetracarboxylicAcidDianhydride: Material
        lateinit var Nitroaniline: Material
        lateinit var ParaPhenylenediamine: Material
        lateinit var KaptonE: Material
        lateinit var Hydroxyquinoline: Material
        lateinit var HydrogenCyanide: Material
        lateinit var AcetoneCyanohydrin: Material
        lateinit var Polymethylmethacrylate: Material
        lateinit var Diacetyl: Material
        lateinit var EthyleneOxide: Material
        lateinit var EthyleneGlycol: Material
        lateinit var Edot: Material
        lateinit var Polystyrene: Material
        lateinit var PolystyreneSulfonate: Material
        lateinit var PedotPSS: Material
        lateinit var PedotTMA: Material
        lateinit var Methylamine: Material
        lateinit var Trimethylamine: Material
        lateinit var TetramethylammoniumChloride: Material
        lateinit var TetramethylammoniumHydroxide: Material
        lateinit var Pyrocatechol: Material
        lateinit var Dichloroethane: Material
        lateinit var Ethylenediamine: Material
        lateinit var EthylenediaminePyrocatechol: Material
        lateinit var Formaldehyde: Material
        lateinit var TetrasodiumEDTA: Material
        lateinit var EDTA: Material
        lateinit var Hexafluoropropylene: Material
        lateinit var FluorinatedEthylenePropylene: Material
        lateinit var Trichloroethylene: Material
        lateinit var ChloroaceticAcid: Material
        lateinit var MalonicAcid: Material
        lateinit var PhosphorylChloride: Material
        lateinit var PhosphonitrilicChlorideTrimer: Material
        lateinit var Fluorobenzene: Material
        lateinit var OctafluoroPentanol: Material
        lateinit var RawPolyphosphonitrileFluoroRubber: Material
        lateinit var PolyphosphonitrileFluoroRubber: Material
        lateinit var Polytetrahydrofuran: Material
        lateinit var Dinitrotoluene: Material
        lateinit var Diaminotoluene: Material
        lateinit var Phosgene: Material
        lateinit var TolueneDiisocyanate: Material
        lateinit var TolueneTetramethylDiisocyanate: Material
        lateinit var RawPolytetramethyleneGlycolRubber: Material
        lateinit var PolytetramethyleneGlycolRubber: Material
        lateinit var DenseHydrazineRocketFuel: Material
        lateinit var Methylhydrazine: Material
        lateinit var MethylhydrazineNitrateRocketFuel: Material
        lateinit var Resorcinol: Material
        lateinit var Fluorotoluene: Material
        lateinit var Difluorobenzophenone: Material
        lateinit var Hydroquinone: Material
        lateinit var Polyetheretherketone: Material
        lateinit var Fluorescein: Material
        lateinit var Erythrosine: Material
        lateinit var Isochloropropane: Material
        lateinit var AceticAnhydride: Material
        lateinit var Dinitrodipropanyloxybenzene: Material
        lateinit var Dibromomethylbenzene: Material
        lateinit var Terephthalaldehyde: Material
        lateinit var PretreatedZylon: Material
        lateinit var Zylon: Material
        lateinit var Diborane: Material
        lateinit var Borazine: Material
        lateinit var Trichloroborazine: Material
        lateinit var GammaButyrolactone: Material
        lateinit var NMethylPyrrolidone: Material
        lateinit var Acetylene: Material
        lateinit var Tetrabromoethane: Material
        lateinit var TerephthalicAcid: Material
        lateinit var Bistrichloromethylbenzene: Material
        lateinit var TerephthaloylChloride: Material
        lateinit var Kevlar: Material
        lateinit var ParaToluicAcid: Material
        lateinit var Methylparatoluate: Material
        lateinit var DimethylTerephthalate: Material
        lateinit var PolyethyleneTerephthalate: Material
        lateinit var Trimethylaluminium: Material
        lateinit var Trimethylgallium: Material
        lateinit var AmmoniumCyanate: Material
        lateinit var Carbamide: Material
        lateinit var Butanol: Material
        lateinit var Tributylamine: Material
        lateinit var Dichloromethane: Material
        lateinit var DiethylEther: Material
        lateinit var AminooxyaceticAcid: Material
        lateinit var BenzylBromide: Material
        lateinit var BenzyltrimethylammoniumBromide: Material
        lateinit var Chlorobutane: Material
        lateinit var TertbutylAlcohol: Material
        lateinit var Indene: Material
        lateinit var Indanone: Material
        lateinit var Truxene: Material
        lateinit var Bromomethane: Material
        lateinit var BromoBromomethylNaphthalene: Material
        lateinit var Bromobutane: Material
        lateinit var Butyllithium: Material
        lateinit var AcetylChloride: Material
        lateinit var Dimethylacetamide: Material
        lateinit var GeodesicPolyarene: Material
        lateinit var Fullerene: Material
        lateinit var Glucose: Material
        lateinit var Fructose: Material
        lateinit var OxalicAcid: Material
        lateinit var Dibromoacrolein: Material
        lateinit var Bromodihydrothiine: Material
        lateinit var BETS: Material
        lateinit var Benzaldehyde: Material
        lateinit var SuccinicAnhydride: Material
        lateinit var NHydroxysuccinimide: Material
        lateinit var SuccinimidylAcetate: Material
        lateinit var DimethylamineHydrochloride: Material
        lateinit var Dimethylformamide: Material
        lateinit var Succinimide: Material
        lateinit var Acetonitrile: Material
        lateinit var Acetamide: Material
        lateinit var Acetaldehyde: Material
        lateinit var Glyoxal: Material
        lateinit var Benzylamine: Material
        lateinit var BenzylChloride: Material
        lateinit var Hexabenzylhexaazaisowurtzitane: Material
        lateinit var Dibenzyltetraacetylhexaazaisowurtzitane: Material
        lateinit var Tetraacetyldinitrosohexaazaisowurtzitane: Material
        lateinit var CrudeHexanitrohexaaxaisowurtzitane: Material
        lateinit var Hexanitrohexaaxaisowurtzitane: Material
        lateinit var Hexamethylenetetramine: Material
        lateinit var CyclotetramethyleneTetranitroamine: Material
        lateinit var Octaazacubane: Material
        lateinit var Dibenzylideneacetone: Material
        lateinit var Pyridine: Material
        lateinit var Bipyridine: Material
        lateinit var Cyclooctadiene: Material
        lateinit var Dichlorocyclooctadieneplatinium: Material
        lateinit var Diiodobiphenyl: Material
        lateinit var TrimethyltinChloride: Material
        lateinit var Cycloparaphenylene: Material
        lateinit var Octene: Material
        lateinit var CarbonNanotube: Material
        lateinit var Sarcosine: Material
        lateinit var Ferrocene: Material
        lateinit var Ferrocenylfulleropyrddolidine: Material
        lateinit var Dimethylaminopyridine: Material
        lateinit var Triphenylphosphine: Material
        lateinit var IsopropylAlcohol: Material
        lateinit var Diisopropylcarbodiimide: Material
        lateinit var PhenylpentanoicAcid: Material
        lateinit var DimethylSulfide: Material
        lateinit var PhenylC61ButyricAcid: Material
        lateinit var PhenylC61ButyricStyrene: Material
        lateinit var FullerenePolymerMatrix: Material
        lateinit var Phosphorene: Material
        lateinit var Methyltrichlorosilane: Material
        lateinit var DiethylSulfide: Material
        lateinit var Guaiacol: Material
        lateinit var Xylenol: Material
        lateinit var Creosol: Material
        lateinit var Methoxycreosol: Material
        lateinit var Phenothiazine: Material
        lateinit var IsopropylChloride: Material
        lateinit var PhenothiazinePropylChloride: Material
        lateinit var Promethazine: Material
        lateinit var Codeine: Material

        // 12001-14000: Unknown Composition Materials
        lateinit var Latex: Material
        lateinit var Resin: Material
        lateinit var RainbowSap: Material

        lateinit var Blood: Material
        lateinit var BloodCells: Material
        lateinit var BloodPlasma: Material
        lateinit var BFGF: Material
        lateinit var EGF: Material
        lateinit var CAT: Material
        lateinit var GreenSapphireJuice: Material
        lateinit var SapphireJuice: Material
        lateinit var RubyJuice: Material

        lateinit var GreenhouseGas: Material
        lateinit var GrapeJuice: Material
        lateinit var RedWine: Material
        lateinit var Vinegar: Material
        lateinit var PotatoJuice: Material
        lateinit var Vodka: Material
        lateinit var Polenta: Material
        lateinit var Coffee: Material
        lateinit var Butter: Material
        lateinit var PurpleDrink: Material
        lateinit var Carbon5Fraction: Material
        lateinit var DimerizedCarbon5Fraction: Material
        lateinit var OliveOil: Material
        lateinit var Fat: Material
        lateinit var Mud: Material
        lateinit var LemonExtract: Material
        lateinit var LimeExtract: Material
        lateinit var OrangeExtract: Material
        lateinit var LemonLimeMixture: Material
        lateinit var LemonLimeSodaSyrup: Material
        lateinit var Etirps: Material
        lateinit var CranberryExtract: Material
        lateinit var CranberrySodaSyrup: Material
        lateinit var CranberryEtirps: Material
        lateinit var CoughSyrup: Material
        lateinit var AppleSyrup: Material
        lateinit var CaneSyrup: Material
        lateinit var AppleCaneSyrup: Material
        lateinit var HardAppleCandySyrup: Material

        lateinit var FreeElectronGas: Material
        lateinit var FermionicUUMatter: Material
        lateinit var BosonicUUMatter: Material
        lateinit var RichNitrogenMixture: Material
        lateinit var RichAmmoniaMixture: Material
        lateinit var SeaWater: Material
        lateinit var AcidicSaltWater: Material
        lateinit var ChalcogenAnodeMud: Material
        lateinit var RareEarthHydroxidesSolution: Material
        lateinit var RareEarthChloridesSolution: Material
        lateinit var BrevibacteriumFlavum: Material
        lateinit var Yeast: Material
        lateinit var CupriavidusNecator: Material

        lateinit var MethylamineMixture: Material
        lateinit var BZMedium: Material
        lateinit var LowPurityEnrichedNaquadahEmulsion: Material
        lateinit var LowPurityNaquadriaEmulsion: Material
        lateinit var BedrockSmoke: Material
        lateinit var BedrockSootSolution: Material
        lateinit var CleanBedrockSootSolution: Material
        lateinit var HeavyBedrockSmoke: Material
        lateinit var MediumBedrockSmoke: Material
        lateinit var LightBedrockSmoke: Material
        lateinit var UltralightBedrockSmoke: Material
        lateinit var HeavyTaraniumGas: Material
        lateinit var MediumTaraniumGas: Material
        lateinit var LightTaraniumGas: Material
        lateinit var BedrockGas: Material
        lateinit var CrudeNaquadahFuel: Material
        lateinit var HeavyNaquadahFuel: Material
        lateinit var MediumNaquadahFuel: Material
        lateinit var LightNaquadahFuel: Material
        lateinit var NaquadahGas: Material
        lateinit var CrackedHeavyTaraniumGas: Material
        lateinit var CrackedMediumTaraniumGas: Material
        lateinit var CrackedLightTaraniumGas: Material
        lateinit var HeavyTaraniumFuel: Material
        lateinit var MediumTaraniumFuel: Material
        lateinit var LightTaraniumFuel: Material
        lateinit var EnrichedBedrockSootSolution: Material
        lateinit var CleanEnrichedBedrockSootSolution: Material
        lateinit var HeavyEnrichedBedrockSmoke: Material
        lateinit var MediumEnrichedBedrockSmoke: Material
        lateinit var LightEnrichedBedrockSmoke: Material
        lateinit var HeavyEnrichedTaraniumGas: Material
        lateinit var MediumEnrichedTaraniumGas: Material
        lateinit var LightEnrichedTaraniumGas: Material
        lateinit var CrackedHeavyEnrichedTaraniumGas: Material
        lateinit var CrackedMediumEnrichedTaraniumGas: Material
        lateinit var CrackedLightEnrichedTaraniumGas: Material
        lateinit var HeavyEnrichedTaraniumFuel: Material
        lateinit var MediumEnrichedTaraniumFuel: Material
        lateinit var LightEnrichedTaraniumFuel: Material
        lateinit var NaquadriaEnergetic: Material
        lateinit var QuasifissioningPlasma: Material
        lateinit var OganessonBreedingBase: Material
        lateinit var UnprocessedNdYAGSolution: Material
        lateinit var MutatedLivingSolder: Material
        lateinit var SodioIndene: Material
        lateinit var SteamCrackedSodioIndene: Material
        lateinit var PhosphoreneSolution: Material

        lateinit var NeutronProtonFermiSuperfluid: Material
        lateinit var HeavyLeptonMixture: Material
        lateinit var QuarkGluonPlasma: Material
        lateinit var HeavyQuarks: Material
        lateinit var LightQuarks: Material
        lateinit var Gluons: Material
        lateinit var HadronicResonantGas: Material
        lateinit var StableBaryonicMatter: Material
        lateinit var HighEnergyQuarkGluonPlasma: Material

        lateinit var DimensionallyShiftedSuperfluid: Material

        @JvmStatic
        fun init()
        {
            GTLiteElementMaterials.init() // 1-2000
            GTLiteFirstDegreeMaterials.init() // 2001-4000
            GTLiteSecondDegreeMaterials.init() // 4001-6000
            GTLiteThirdDegreeMaterials.init() // 6001-8000
            GTLiteOrganicChemistryMaterials.init() // 8001-12000
            GTLiteUnknownCompositionMaterials.init() // 12001-14000
        }

    }

}