package gregtechlite.gtlitecore.loader.recipe.chain

internal object ChemistryRecipeList
{

    // @formatter:off

    fun init()
    {
        OilsChain.init()
        RubbersChain.init()
        PolymersChain.init()
        AlloysChain.init()
        BSCCOChain.init()
        YBCOChain.init()
        DyesChain.init()
        MicaInsulatorChain.init()
        OxidesChain.init()
        AmmoniaChain.init()
        PalladiumAcetateChain.init()
        LithiumTitanateChain.init()
        RubidiumTitanateChain.init()
        NanoparticlesChain.init()
        QuantumDotsChain.init()
        OzoneChain.init()
        MagnetoResonaticChain.init()
        HydrogenPeroxideChain.init()
        HydrazineChain.init()
        GrapheneChain.init()
        CitricAcidChain.init()
        GrowthMediumChain.init()
        KaptonChain.init()
        PMMAChain.init()
        EthyleneGlycolChain.init()
        PEDOTChain.init()
        MethylamineChain.init()
        EDTAChain.init()
        ButyllithiumChain.init()
        EtchingMaterialsChain.init()
        FEPChain.init()
        BZMediumChain.init()
        PhosphorusChain.init()
        RocketFuelsChain.init()
        ReactorModeratorChain.init()
        SuperheavyElementsChain.init()
        PEEKChain.init()
        ZylonChain.init()
        PotassiumPermanganateChain.init()
        BoronNitrideChain.init()
        AcetyleneChain.init()
        KevlarChain.init()
        GalliumNitrideChain.init()
        PETChain.init()
        LithiumNiobateChain.init()
        ChloridesChain.init()
        NdYAGChain.init()
        DiethylEtherChain.init()
        ParticlesChain.init()
        CosmicNeutroniumChain.init()
        HalkoniteSteelChain.init()
        LeadSiliconGlassChain.init()
        ThoriumYttriumGlassChain.init()
        HeatExchangeChain.init()
        MutatedLivingSolderChain.init()
        FullereneChain.init()
        DegenerateRheniumChain.init()
        ActiniumSuperhydrideChain.init()
        BETSPerrhenateChain.init()
        QuarksChain.init()
        SilicaGelChain.init()
        HNIWChain.init()
        HMXChain.init()
        OctaazacubaneChain.init()
        ChargersChain.init()
        NanotubesChain.init()
        InfinityChain.init()
        MagnetiumChain.init()
        HypogenChain.init()
        ShirabonChain.init()
        FullerenePolymerMatrixChain.init()
        LuTmYVOChain.init()
        SiliconNitrideChain.init()
        NanitesChain.init()
        AntimatterChain.init()
        TesseractsChain.init()
        CreonMellionChain.init()
        PrHoYLFChain.init()
        PhononChain.init()
        CosmicFabricChain.init()
        AscorbicAcidChain.init()
        AlgaeChain.init()
        BatteriesChain.init()
        ChromaticGlassChain.init()
        MHDCSMChain.init()
        EternityChain.init()
        BlackHolesChain.init()
        HeavyConductiveMixtureChain.init()
        PolymerInsulatorChain.init()
    }

    // @formatter:on

}